spring:
  application:
    name: mystipass
  shell:
    interactive:
      enabled: false
    command:
      script:
        enabled: false
      quit:
        enabled: false
      history:
        enabled: false
      stacktrace:
        enabled: false
      help:
        command-template: classpath:template/command-help.stg
        commands-template: classpath:template/commands-help.stg
  main:
    banner-mode: off

logging:
  level:
    root: off

