spring:
  application:
    name: mystipass
  shell:
    interactive:
      enabled: false
    command:
      script:
        enabled: false
      quit:
        enabled: false
      history:
        enabled: false
      stacktrace:
        enabled: false
  main:
    banner-mode: off

logging:
  level:
    root: off

